///$tab 0_EMA_MAP
/* 
Creation of look up table
Static never changing tables
*/

EMA_dates:
Mapping
Load * Inline [
    brand,			EMA_Date
    OLUMIANT,		20170201 
    XELJANZ,		20170301
    RINVOQ,			20191201
    JYSELECA,		20200901
];

Reimbursement_dates:
Mapping
Load * Inline [
    brand,			Reimbursement_Date
    OLUMIANT,		20170901 
    XELJANZ,		20171101
    RINVOQ,			20200701
    JYSELECA,		20210501
];