///$tab Main
SET ThousandSep=',';
SET DecimalSep='.';
SET MoneyThousandSep=',';
SET MoneyDecimalSep='.';
SET MoneyFormat='$#,##0.00;-$#,##0.00';
SET TimeFormat='h:mm:ss TT';
SET DateFormat='M/D/YYYY';
SET TimestampFormat='M/D/YYYY h:mm:ss[.fff] TT';
SET FirstWeekDay=6;
SET BrokenWeeks=1;
SET ReferenceDay=0;
SET FirstMonthOfYear=1;
SET CollationLocale='en-US';
SET CreateSearchIndexOnReload=1;
SET MonthNames='Jan;Feb;Mar;Apr;May;Jun;Jul;Aug;Sep;Oct;Nov;Dec';
SET LongMonthNames='January;February;March;April;May;June;July;August;September;October;November;December';
SET DayNames='Mon;Tue;Wed;Thu;Fri;Sat;Sun';
SET LongDayNames='Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday';
SET NumericalAbbreviation='3:k;6:M;9:G;12:T;15:P;18:E;21:Z;24:Y;-3:m;-6:μ;-9:n;-12:p;-15:f;-18:a;-21:z;-24:y';


Set vQVD_Migration_Path 		= 'lib://Market View/1.QVD/5.Migration/';

Set vGersOrigin 				= 'lib://AttachedFiles/GAL_BIOTHERAPIESGERSORIGIN_ORIGIN_UGA_4358010001000701_M202105.CSV'; //y
Set vGersProductMasterHop 		= 'lib://AttachedFiles/GAL_GALAPAGOSHOP_SIG_UGA_4358070001000101_M202105.xlsx';  //y
Set vGersProductMasterOffice 	= 'lib://AttachedFiles/GAL_GALAPAGOSOFFICINE_SIG_UGA_4358050001000101_M202105.xlsx'; //y
Set vGersStathop				= 'lib://AttachedFiles/GAL_BIOTHERAPIESSTATHOP_STATHOP_PDV_4358030001000101_M202105.csv'; //y
Set vGersStathopExcel			= 'lib://AttachedFiles/GAL_BIOTHERAPIESSTATHOP_STATHOP_PDV_4358030001000101_M202105.xlsx'; //y
Set vGersOriginSecto			= 'lib://AttachedFiles/GAL_BIOTHERAPIESGERSORIGINSPE_ORIGINS_SECTO_4358020001000701_M202105.csv'; //y
Set vGersPDV					= 'lib://AttachedFiles/PDVTOTREP_202105.csv'; //y

/*
Two history files have been provided:
1. Stathop 			- GAL_BIOTHERAPIESSTATHOP_STATHOP_PDV_4358030001000103_M201912
2. GERS Origin 		- GAL_BIOTHERAPIESGERSORIGIN_ORIGIN_UGA_4358010001000701_M202006
3. Territory look up file - Territory Structure - 2021-01-08.xlsx
*/